#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DP3 connected') ]]; then
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output DP3 --mode 1920x1080 --rotate normal --right-of eDP1 
fi

bspc monitor eDP1 -d 1 2 3 4 
bspc monitor DP3 -d 5 6 7 8

bspc config border_width         3
bspc config window_gap         	 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM coloring ####
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5b9c6d" 
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

#bspc rule -a Gimp desktop='^8' state=floating
#bspc rule -a firefoxdeveloperedition desktop='^2' focus=on follow=on
#bspc rule -a jetbrains-idea desktop='^3' focus=on follow=on
#bspc rule -a Code desktop='^4' focus=on follow=on
#bspc rule -a jetbrains-datagrip desktop='^5' focus=on follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a feh state=floating
#bspc rule -a Pcmanfm state=floating 
#bspc rule -a vlc state=floating rectangle=600x400+500+100
#bspc rule -a mpv state=pseudo_tiled
#bspc rule -a Skype desktop='^9' focus=on follow=on
#bspc rule -a TelegramDesktop desktop='^9' focus=on follow=on

# Run polybar
$HOME/.config/polybar/launch.sh

# Fix Cursor display X when not over window
xsetroot -cursor_name left_ptr &

# Display wallpaper
feh --bg-fill --randomize ~/.config/wallpapers/bg.png

# Run Picom
picom &
