#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	 4 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a firefoxdeveloperedition desktop='^2' focus=on follow=on
bspc rule -a jetbrains-idea desktop='^3' focus=on follow=on
bspc rule -a Code desktop='^4' focus=on follow=on
bspc rule -a jetbrains-datagrip desktop='^5' focus=on follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a Pcmanfm state=floating 
bspc rule -a vlc state=floating rectangle=600x400+500+100
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Skype desktop='^9' focus=on follow=on
bspc rule -a TelegramDesktop desktop='^9' focus=on follow=on

# Run polybar
$HOME/.config/polybar/launch.sh

# Fix Cursor display X when not over window
xsetroot -cursor_name left_ptr &

# Display wallpaper
feh --bg-fill --randomize ~/.config/wallpapers/bg.jpeg

# Run Picom
picom &
